### PR TITLE
Activation Updates

### PR DESCRIPTION
**Pull request by mgorbach**
Implemented:
- Cleaned-up activation: Get rid of the overlay window and magic button.
- Three-finger, three-tap gesture to activate (installed using a public method of a target `UIView`)
- Public access to the `viewController` to present.
- Public access to `present` and `dismiss` methods.
- Update `Readme` for these changes.

### CODE REVIEW

**Comment by mgorbach** [comment]
@KingOfBrian can you take a look at this?
@adamhrz these are the changes Brian requested before your adoption.

**Comment by KingOfBrian** [comment]
So I would do a 2 finger triple tap so it can be used in the simulator.   Can't do a 3 finger gesture.

**Comment by ZevEisenberg** [comment]
3-finger double tap is probably nicer on hardware, though. Any sense in doing that for device, and two-finger double tap in simulator? Or would that get too confusing?

**Comment by mgorbach** [comment]
@KingOfBrian going point. @ZevEisenberg I don't want differing activation gestures, so I think I'll go with 2-finger triple-tap.
@KingOfBrian Anything else here you think needs tweaking?

**Pull request merged**
